version: '3'
services:
  # nginx:
  #   restart: always
  #   depends_on:
  #     - api
  #     - client
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
  postgres:
    container_name: postgres
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=icarus2io
  redis:
    container_name: redis
    image: "redis:6.2.4-alpine"
  api:
    container_name: api
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment: 
      - DATABASE_URL=postgres://user:password@postgres:5432/icarus2io
    ports:
      - '3000:3000'
  client:
    container_name: client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '8000:8000'

